### ISSUE TITLE
Definir la clase Articulo

### ISSUE THREAD

**Issue by noise-kngdm** [amerigal/proyecto_iv#6]
Para comenzar con la **[M0]**, relacionada con la [[HU1]](https://github.com/amerigal/proyecto_iv/issues/2), es necesario definir la estructura de datos básica de la que harán uso los recibos: los artículos.
Una instancia de esta clase, albergará la siguiente información:
- Descripción del artículo, cómo es descrito por el vendedor o fabricante.
- Fabricante del artículo.
- Tipo de artículo. Se diferencia de la descripción del artículo en que este atributo servirá para agrupar a artículos similares, por ejemplo, todos los yogures o cremas faciales.
- Precio.
- Descuento del artículo, si lo tiene.
- Tipo de IVA.
- Fecha de fabricación/producción.
- Lugar de fabricación/producción.

**Comment by amerigal** [comment]
Me parece adecuado partir del artículo como objeto base sobre el que construir los recibos. Del mismo modo, veo muy acertada la inclusión del atributo 'Tipo de artículo', pues en efecto será interesante poder agrupar aquellos de características similares.

Por otro lado, hay ciertos atributos de los que creo que en general no será posible obtener información partiendo de un recibo. Me refiero al fabricante, fecha y lugar de fabricación del artículo.

**Comment by amerigal** [comment]
Comento aquí para que quede constancia de la decisión tomada en #7 de no incluir la información Descuento del artículo en la clase Articulo
